CREATE DATABASE GERENCIAPEDIDOS;

USE GERENCIAPEDIDOS;

CREATE TABLE PRODUTO(
	COD_PRODUTO VARCHAR(10), 
	DESCRICAO VARCHAR(100), 
    PRECO DECIMAL, 
    PRIMARY KEY(COD_PRODUTO));

CREATE TABLE PEDIDO(
	COD_PEDIDO INT auto_increment, 
    DATA DATE, PRIMARY KEY(COD_PEDIDO));

CREATE TABLE ITEM_PEDIDO(
	COD_PEDIDO_FK INT, 
    COD_PRODUTO_FK VARCHAR(10), 
    QUANTIDADE INT, 
    FOREIGN KEY(COD_PEDIDO_FK) REFERENCES PEDIDO(COD_PEDIDO),  
    FOREIGN KEY(COD_PRODUTO_FK) REFERENCES PRODUTO(COD_PRODUTO),
    PRIMARY KEY(COD_PEDIDO_FK,COD_PRODUTO_FK));
